Repository googleapis/nodejs-iam-credentials, pull requests merged in 2021-02, with the labels that each got.

#11 chore: update CODEOWNERS config
  .github/CODEOWNERS
Labels: automerge, cla: yes

#10 build: migrate to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
Labels: automerge, cla: yes

#14 chore: update flakybot config and module naming
  .jsdoc.js
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  linkinator.config.json
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/gapic_metadata.json
  src/v1/i_a_m_credentials_client.ts
  src/v1/index.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_i_a_m_credentials_v1.ts
Labels: cla: yes, context: partial

#19 chore: migrate to flakybot and update sample list
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: cla: yes, context: full
